const select = document.getElementById("cities-name");
const cityList = {
  Agra: "Agra",
  Ahmedabad: "Ahmedabad",
  Ajmer: "Ajmer",
  Aligarh: "Aligarh",
  Allahabad: "Allahabad",
  Amravati: "Amravati",
  Amritsar: "Amritsar",
  Aurangabad: "Aurangabad",
  Bareilly: "Bareilly",
  Belgaum: "Belgaum",
  Bengaluru: "Bengaluru",
  Bhilai: "Bhilai",
  Bhopal: "Bhopal",
  Bhubaneswar: "Bhubaneswar",
  Bijnor: "Bijnor",
  Chandigarh: "Chandigarh",
  Chennai: "Chennai",
  Coimbatore: "Coimbatore",
  Cuttack: "Cuttack",
  Dehradun: "Dehradun",
  Delhi: "Delhi",
  Dhanbad: "Dhanbad",
  Faridabad: "Faridabad",
  Ghaziabad: "Ghaziabad",
  Gorakhpur: "Gorakhpur",
  Guntur: "Guntur",
  Gurugram: "Gurugram",
  Guwahati: "Guwahati",
  Gwalior: "Gwalior",
  Hyderabad: "Hyderabad",
  Indore: "Indore",
  Jabalpur: "Jabalpur",
  Jaipur: "Jaipur",
  Jalandhar: "Jalandhar",
  Jammu: "Jammu",
  Jamnagar: "Jamnagar",
  Jamshedpur: "Jamshedpur",
  Jhansi: "Jhansi",
  Jodhpur: "Jodhpur",
  Kanpur: "Kanpur",
  Kochi: "Kochi",
  Kolhapur: "Kolhapur",
  Kolkata: "Kolkata",
  Kota: "Kota",
  Kozhikode: "Kozhikode",
  Lucknow: "Lucknow",
  Ludhiana: "Ludhiana",
  Madurai: "Madurai",
  Mangalore: "Mangalore",
  Meerut: "Meerut",
  Moradabad: "Moradabad",
  Mumbai: "Mumbai",
  Mysuru: "Mysuru",
  Nagpur: "Nagpur",
  Nashik: "Nashik",
  NaviMumbai: "Navi Mumbai",
  Noida: "Noida",
  Patna: "Patna",
  PimpriChinchwad: "Pimpri Chinchwad",
  Prayagraj: "Prayagraj",
  Pune: "Pune",
  Raipur: "Raipur",
  Rajkot: "Rajkot",
  Ranchi: "Ranchi",
  Saharanpur: "Saharanpur",
  Salem: "Salem",
  Shimla: "Shimla",
  Siliguri: "Siliguri",
  Srinagar: "Srinagar",
  Surat: "Surat",
  Thane: "Thane",
  Tiruchirappalli: "Tiruchirappalli",
  Tiruppur: "Tiruppur",
  Udaipur: "Udaipur",
  Ujjain: "Ujjain",
  Vadodara: "Vadodara",
  Varanasi: "Varanasi",
  VasaiVirar: "Vasai Virar",
  Vijayawada: "Vijayawada",
  Visakhapatnam: "Visakhapatnam",
  Warangal: "Warangal",
};

Object.values(cityList).forEach((city) => {
  const option = document.createElement("option");
  option.value = city;
  option.textContent = city;
  select.appendChild(option);
});
